#[derive(Default)]
pub struct VehicleData {
    pub engine_rpm: f32,
    pub vehicle_speed: u8,
    pub coolant_temp: i16,
    pub throttle_pos: u8,
    pub engine_load: u8,
    pub intake_pressure: u8,
    pub timing_advance: f32,
    pub intake_temp: i16,
    pub maf_sensor: f32,
    pub fuel_pressure: u8,
    pub o2_voltage: f32,
    pub fuel_level: u8,
    pub baro_pressure: u8,
    pub ambient_temp: i16,
    pub fuel_rail_pressure: u16,
    pub commanded_egr: u8,
    pub egr_error: f32,
    pub fuel_trim_short_b1: f32,
    pub fuel_trim_long_b1: f32,
    pub command_equiv_ratio: f32,
    pub control_module_voltage: f32,
}
